### ISSUE TITLE
Data corruption crash

### ISSUE THREAD

**Issue by xylix** [apinf/openapi-designer#202]
This needs to be looked at.

```
TypeError: Cannot create property 'key' on string ''
at Arrayfield.setValue (http://localhost:9000/scripts/app-bundle.js:1563:31)
at Objectfield.setValue (http://localhost:9000/scripts/app-bundle.js:2161:31)
at Typefield.setValue (http://localhost:9000/scripts/app-bundle.js:3346:20)
at Arrayfield.setValue (http://localhost:9000/scripts/app-bundle.js:1565:31)
at Linkfield.setValue (http://localhost:9000/scripts/app-bundle.js:1954:15)
at Objectfield.setValue (http://localhost:9000/scripts/app-bundle.js:2161:31)
at new App (http://localhost:9000/scripts/app-bundle.js:66:22)
at Object.invoke (http://localhost:9000/scripts/vendor-bundle.js:18807:14)
at InvocationHandler.invoke (http://localhost:9000/scripts/vendor-bundle.js:18772:168)
at Container.invoke (http://localhost:9000/scripts/vendor-bundle.js:19036:25)
at StrategyResolver.get (http://localhost:9000/scripts/vendor-bundle.js:18489:37)
at Container.get (http://localhost:9000/scripts/vendor-bundle.js:18975:23)
at http://localhost:9000/scripts/vendor-bundle.js:29883:73
at run (http://localhost:9000/scripts/vendor-bundle.js:9835:22)
at http://localhost:9000/scripts/vendor-bundle.js:9848:28
at MutationObserver.flush (http://localhost:9000/scripts/vendor-bundle.js:7133:9)
```

**Comment by xylix** [comment]
Caused by OAuth2 in Security Definitions.
